Enable to remove node in the distributed environment
apache/incubator-iotdb pull request #1634
Opened 2020-08-19 03:32 UTC by wyh-ztf

2020-08-19 03:46 UTC, neuyilan requested changes
Good Job!

2020-08-19 03:46 UTC, neuyilan commented on cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java
> +      logger.error("When default_ replica_ When num = 1 or 2, the node cannot be removed temporarily, because in the current implementation, datagroup cannot achieve majority agreement");
“default_ replica_ When“ what this mean?

2020-08-19 03:46 UTC, neuyilan commented on cluster/src/assembly/resources/sbin/remove-node.sh
> +  meta_port=`sed '/^internal_meta_port=/!d;s/.*=//' $IOTDB_CONF/iotdb-cluster.properties`
code format

2020-08-20 01:23 UTC, jt2594838 requested changes
Thanks for your contribution, but there are a few points that we should explain to you:
1. The node being removed is not bound to a local node, and it is very likely that we remove a node by another node, especially when the node to be removed is unavailable. So the node should be set by the user manually.
2. The removal of a node does not require the agreement of any data group, and the only thing that matters is that the meta group reaches an agreement, and data groups will be adjusted accordingly, so it does not concern the number of replicas.
3. Node-removal is still under development and requires testing, so it would be better not to pay too much attention to it currently.
4. The whole protect follows Google-style which is described in the project root directory, please see to it.

2020-09-03 01:49 UTC, wyh-ztf commented
> explain

2020-09-03 01:49 UTC, closed without merging